### ISSUE TITLE
Qualcomm quick charge support

### ISSUE THREAD

**Issue by Grv-Singh** [PixelExperience-Devices/device_xiaomi_lavender#10]
Does the 4.4.232-OniiChanKernel-Faham-X-12.0+
#1 Fri Aug 14 23:20:23 UTC 2020
Kernel supports Qualcomm quick charge 4 ?

 ![20200908_211049-02.jpeg](https://user-images.githubusercontent.com/12825441/92499225-3ffef880-f219-11ea-9eea-a4e783f6f861.jpeg)
Here's a compatible charger that's being used (min. 5v/2A).

![Screenshot_20200908-204133~2-01.jpeg](https://user-images.githubusercontent.com/12825441/92499956-24482200-f21a-11ea-8165-9d107464d1c1.jpeg)
Here's ampere report after 30 minutes of charging, please notice the voltage to be just around 4V.

Do you think this is in scope for discussion?
Could respond ?

**Comment by sohamxda7** [comment]
If xiaomi stock kernel supports it then it will definite support also
