### ISSUE TITLE
Fingerprint problem

### ISSUE THREAD

**Issue by superislam** [PixelExperience-Devices/device_xiaomi_lavender#11]
Hello i have a problem with fingerprint it stops working sometimes till i reboot the phone  and here is the log
[logcat_01-10-2021_19-12-32.txt](https://github.com/PixelExperience-Devices/device_xiaomi_lavender/files/5821109/logcat_01-10-2021_19-12-32.txt)

**Comment by sohamxda7** [comment]
take fresh log, that log is derped
